# Site settings
title: CI and CD with GitHub
description: A demo blog
email: brent@github.com
twitter_username: brntbeer
github_username:  brntbeer
baseurl:
url: https://brntbeer-ci-cd-workshop.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
